#!/usr/bin/env bash
set -e

#Check if .env file exists
if [ -f .env ]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ $line =~ ^[^#]*=.* ]]; then
            export "$line"
        fi
    done <.env
fi

# Check if the required variables are set
if [ -z "$AWS_ACCESS_KEY" ] || [ -z "$AWS_SECRET_KEY" ]; then
    echo "Error: AWS_ACCESS_KEY and AWS_SECRET_KEY must be set in .env file or in environment variables"
    exit 1
fi

echo "About to update serverless API Keys for AWS"
serverless config credentials \
    --provider aws \
    --key "$AWS_ACCESS_KEY" \
    --secret "$AWS_SECRET_KEY"
echo "Updated serverless API Keys"
